version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_DATABASE=test
      - DB_MYSQLDB_HOST=gateway01.eu-central-1.prod.aws.tidbcloud.com
      - DB_MYSQLDB_PORT=4000
      - DB_MYSQLDB_USER=dEXG5DU43c68xUs.root
      - DB_MYSQLDB_PASSWORD=700H1vpRz60P7g8V
      - DB_MYSQLDB_SSL=true
      - DB_MYSQLDB_SSL_CA=/etc/ssl/certs/ca-certificates.crt
      - N8N_ENCRYPTION_KEY=whc20DEqUvG+28CUVDDLRJZOHnr32ktg
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
